.Dd February 14, 2021
.Dt POSIX-CD 1
.Os
.Sh NAME
.Nm posix-cd
.Nd change the current working directory to a given directory, then execute a program
.Sh SYNOPSIS
.Nm
.Op Fl L | Fl P
.Ar dir
.Ar prog...
.Sh DESCRIPTION
.Nm
changes the current working directory to
.Ar dir
according to the POSIX specification for a
.Ql cd
external utility[1].
Then, if
.Ar prog...
is not empty, it execs into it.
.Pp
When execline has been configured with the
.Ql --enable-pedantic-posix
option, the
.Pa cd
command is a symbolic link to it.
So scripts calling
.Pa cd
will use
.Nm .
When this configuration option has not been given,
.Pa cd
is a symbolic link to
.Xr execline-cd 1 .
.Pp
.Nm
fully conforms to the POSIX specification[1].
When
.Ar prog...
is not empty, the behaviour of a
.Ql cd
utility is not specified by POSIX, so
.Nm
extends the spec to be actually useful and usable in an execline
program with the same interface as the regular execline
.Ql cd
command
.Po
cf.\&
.Xr execline-cd 1
.Pc .
.Pp
Nobody ever executes or needs the external version (i.e. not a shell
builtin) of the POSIX
.Ql cd
command.
Compared to execline's regular
.Pa cd
binary,
.Xr execline-cd 1 ,
.Nm
is uselessly bloated and slow.
The only reason it exists is that some distributions refuse to package
execline correctly unless it is strictly POSIX-compliant; the
.Ql --enable-pedantic-posix
configure option is there to satisfy their requirements.
.Sh SEE ALSO
.Xr emptyenv 1 ,
.Xr envfile 1 ,
.Xr exec 1 ,
.Xr execline-cd 1 ,
.Xr execline-umask 1 ,
.Xr exit 1 ,
.Xr export 1 ,
.Xr fdblock 1 ,
.Xr fdclose 1 ,
.Xr fdmove 1 ,
.Xr fdreserve 1 ,
.Xr fdswap 1 ,
.Xr getcwd 1 ,
.Xr getpid 1 ,
.Xr heredoc 1 ,
.Xr piperw 1 ,
.Xr posix-umask 1 ,
.Xr redirfd 1 ,
.Xr trap 1 ,
.Xr tryexec 1 ,
.Xr unexport 1 ,
.Xr wait 1 ,
.Xr withstdinas 1
.Pp
[1]
.Lk https://pubs.opengroup.org/onlinepubs/9699919799/utilities/cd.html
.Pp
This man page is ported from the authoritative documentation at:
.Lk https://skarnet.org/software/execline/posix-cd.html
.Sh AUTHORS
.An Laurent Bercot
.An Alexis Ao Mt flexibeast@gmail.com Ac (man page port)
