.Dd February 14, 2021
.Dt UNEXPORT 1
.Os
.Sh NAME
.Nm unexport
.Nd remove a variable from the environment, then execute a program
.Sh SYNOPSIS
.Nm
.Ar var
.Ar prog...
.Sh DESCRIPTION
.Nm
removes the
.Ar var
variable from the environment, then
.Xr exec 3 Ns
s into
.Ar prog
with its arguments.
.Pp
Unsetting
.Ar var
is quite different from setting it to an empty value.
Shell scripts usually won't make the distinction; execline does.
.Sh SEE ALSO
.Xr emptyenv 1 ,
.Xr envfile 1 ,
.Xr exec 1 ,
.Xr execline-cd 1 ,
.Xr execline-umask 1 ,
.Xr exit 1 ,
.Xr export 1 ,
.Xr fdblock 1 ,
.Xr fdclose 1 ,
.Xr fdmove 1 ,
.Xr fdreserve 1 ,
.Xr fdswap 1 ,
.Xr getcwd 1 ,
.Xr getpid 1 ,
.Xr heredoc 1 ,
.Xr piperw 1 ,
.Xr posix-cd 1 ,
.Xr posix-umask 1 ,
.Xr redirfd 1 ,
.Xr trap 1 ,
.Xr tryexec 1 ,
.Xr wait 1 ,
.Xr withstdinas 1 ,
.Xr exec 3
.Pp
This man page is ported from the authoritative documentation at:
.Lk https://skarnet.org/software/execline/unexport.html
.Sh AUTHORS
.An Laurent Bercot
.An Alexis Ao Mt flexibeast@gmail.com Ac (man page port)
