.Dd February 14, 2021
.Dt PIPERW 1
.Os
.Sh NAME
.Nm piperw
.Nd create a pipe (an anonymous one), then execute a program
.Sh SYNOPSIS
.Nm
.Ar fdr
.Ar fdw
.Ar prog...
.Sh DESCRIPTION
.Nm
creates a pipe with descriptor
.Ar fdw
as the writing end and descriptor
.Ar fdr
as the reading end.
It then execs into
.Ar prog
with its arguments.
.Sh SEE ALSO
.Xr emptyenv 1 ,
.Xr envfile 1 ,
.Xr exec 1 ,
.Xr execline-cd 1 ,
.Xr execline-umask 1 ,
.Xr exit 1 ,
.Xr export 1 ,
.Xr fdblock 1 ,
.Xr fdclose 1 ,
.Xr fdmove 1 ,
.Xr fdreserve 1 ,
.Xr fdswap 1 ,
.Xr getcwd 1 ,
.Xr getpid 1 ,
.Xr heredoc 1 ,
.Xr posix-cd 1 ,
.Xr posix-umask 1 ,
.Xr redirfd 1 ,
.Xr trap 1 ,
.Xr tryexec 1 ,
.Xr unexport 1 ,
.Xr wait 1 ,
.Xr withstdinas 1
.Pp
This man page is ported from the authoritative documentation at:
.Lk https://skarnet.org/software/execline/piperw.html
.Sh AUTHORS
.An Laurent Bercot
.An Alexis Ao Mt flexibeast@gmail.com Ac (man page port)
